/// Flutter icons DrawerIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DrawerIcons
///      fonts:
///       - asset: fonts/DrawerIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DrawerIcons {
  DrawerIcons._();

  static const _kFontFam = 'DrawerIcons';
  static const String? _kFontPkg = null;

  static const IconData home =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
